### ISSUE TITLE
Deployment with gh-pages 

### ISSUE THREAD

**Issue by Mar12358** [Mar12358/Portfolio#18]
This is the link for my online version with [gh-pages](https://mar12358.github.io/Portfolio/)

**Comment by zieeco** [comment]
# status: APPROVED :green_circle: :100: 

Hi, @Mar12358 , 


<img height="230" src="https://media0.giphy.com/media/7hyhCyGbFX50Vc9jah/giphy.gif"/>

Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Good commit messages 👍 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
