### ISSUE TITLE
Bug find and fix session

### ISSUE THREAD

**Issue by toyman640** [Mar12358/Portfolio#30]
- The first section of the page is blurred out without pop up window, 
 On line 7 you already toggled the **'.blend mode'** class before calling the **clickMenu()** function.
Try to move the code on line 7 into the function.
https://github.com/Mar12358/Portfolio/blob/3fabc00ae246259479216a5e9248560675045308/main.js#L7-L15

- The stacks buttons display **HTML** buttons twice on the pop-up card.
 On line 46 you already initialized a child element for the stacks button here
https://github.com/Mar12358/Portfolio/blob/3fabc00ae246259479216a5e9248560675045308/main.js#L46

Try to take out line 46 and let the loop on line 55 handle the display of the Stacks buttons
https://github.com/Mar12358/Portfolio/blob/3fabc00ae246259479216a5e9248560675045308/main.js#L55-L57

**Comment by Mar12358** [comment]
This is out of date and already assesed. Closing.
